### ISSUE TITLE
Invalid request signature detected during tree data manage action

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-tree-manager#150] opened 2016-12-27 00:44 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  Tree was working ok until recent updates adding security to the tree manager.

I receive the following error when trying to edit an entry.
OLD HASH:

NEW HASH:
a38765c14d6deca7202b52c3d8464e4beb3768cf8f872a54af94d36f6cfc91d6common\models\Category111/gsys/admin/category@kvtree/views/_formw0-nodesel[]{"1":"","2":"@app/views/category/_form","3":"","4":"","5":""}"text"{"depth":"","glue":" » ","activeCss":"kv-crumb-active","untitled":"Untitled"}

I have also tried using a different browser and deleting cache and cookies.

**Comment by neutron3** [comment] 2016-12-27 05:48
I have a same problem...
`OLD HASH:

NEW HASH:
6690903f23648f0a509a455c70db56040c32899aaedce87e50940ef05e4ad228rootbackend\modules\catalog\models\Catalog111/admin/catalog/index@kvtree/views/_formw0-nodesel[]{"1":"","2":"","3":"","4":"","5":""}"text"{"depth":"","glue":" » ","activeCss":"kv-crumb-active","untitled":"Без названия"}`

**Comment by kartik-v** [comment] 2016-12-27 05:59
Seems to be some problem with your web assets and cache. Did you cross check with the demos page for example?

The OLD HASH and NEW HASH must match.

**Comment by neutron3** [comment] 2016-12-27 06:17
All setup of treeview i make in full accordance with instruction, no skipped steps...

For removing error I try to clear cache in browser and use different browsers,

I try to use treeview  with this code and without it:

**Enable and disable cache** in module config
```
'unsetAjaxBundles' => [
                'yii\web\YiiAsset',
                'yii\web\JqueryAsset',
                'yii\widgets\ActiveFormAsset',
                'yii\validators\ValidationAsset'
            ]
```
**unset bundles** in widget settings
'cacheSettings' => ['enableCache' => false]

No result.
Sorry for my English, it's not my native language

**Comment by kartik-v** [comment] 2016-12-27 06:27
I am not talking about the settings in extension (for cache).. but your yii2 app web assets folder and the browser cache. You may need to cleanup your runtime web assets, clean up browser cache, and restart and try.

**Comment by kartik-v** [comment] 2016-12-27 06:29
I am not talking about the settings in extension (for cache).. but your yii2 app runtime and web assets You may need to cleanup your runtime web assets, clean up browser cache, and restart and try.

Check the source of the page and find out if the kvtree.js loading on your page exactly matches the [latest kvtree.js for the extension](https://github.com/kartik-v/yii2-tree-manager/blob/master/assets/js/kv-tree.js).

**Comment by neutron3** [comment] 2016-12-27 06:39
I cleanup runtime/cache and web/assets folders.
kvtree.js is 100% same (I install latest treeview 2-3 hours ago and compare files in IDE)
No result :(

**Comment by kartik-v** [comment] 2016-12-27 07:04
- Have you customized, changed, or extended any of the extension classes like `TreeView`, `NodeController`? If so, you would need to try first with the base extension classes provided as is with the extension. You maybe overriding some methods in your extended class which maybe causing the Old Hash to be null.
- Are you writing your own custom actions to manage the tree nodes (instead of extension provided `NodeController`). 
- if you have everything as provided by this extension (without any changes to the code from your side)... then you may post your TreeView configuration and how you are calling it for verifying.... since your use case cannot be reproduced.

**Comment by kartik-v** [comment] 2016-12-27 07:10
The above comment was issue check for @maz0717.

 @neutron3 your use case is for CREATE NEW ROOT, and I can confirm the bug... will note it as a bug here and provide a fix.

**Comment by kartik-v** [comment] 2016-12-27 07:43
@neutron3 the create node issue is resolved via #151.

@maz0717 you may confirm if the above comments solve your issue and you have the latest code and I will reopen the issue.

**Comment by maz0717** [comment] 2016-12-28 02:07
1.  I have updated to the latest version.
2.  I have cleared the asset directory.
3.  I have cleared the browser cache.
4.  I have tried using a different browser.

Two things to note that may be causing issues:
1.  The tree is created via created via the command line, and not the interface.
2.  While I have no customizations of yii2-tree-manager, I do have customizations of  yii2-nested-sets, The customizations can be seen in my github copy.  They add a path attribute and remove the protected attribute from a couple of functions.  

Here is my config, as requested:
        'treemanager' => [
            'class' => '\kartik\tree\Module',
            'treeStructure' => [
                // 'treeAttribute' => 'parent_id',
				'depthAttribute' => 'lvl'
            ],
            'dataStructure' => [
                'keyAttribute' => 'category_id',
                'nameAttribute' => 'label'
            ],

**Comment by kartik-v** [comment] 2016-12-28 15:58
Ok... I think hash signatures will not work via console app... as it will not have a view or JavaScript execution engine, Will update.

**Closed** 2016-12-28 16:41 UTC
Labels: enhancement

**Comment by pczi** [comment] 2017-03-14 18:40
The only way I found to bypass the error, is to bypass the checkSignature function in controllers/nodeController:
    protected static function checkSignature($action, $data = [])
    {
        return; <- add this line

I do not really understand the function, in case 'manage' for example, you set $treeManageHash = null, which is the OLDHASH and then you compare this NULL value to a calculated NEWHASH.

**Comment by kartik-v** [comment] 2017-03-15 02:32
> I do not really understand the function, in case 'manage' for example, you set $treeManageHash = null, which is the OLDHASH and then you compare this NULL value to a calculated NEWHASH.

This is incorrect. `$treeManageHash` is derived from the POST data and the `extract` command is supposed to overwrite this variable with value. So it seems for your case for some reason this data is not being submitted via POST (during save of the tree node). You need to check if you have the right latest JAVASCRIPT and assets from extension being loaded (or you have caching issues on your client running old stale assets). Note the `checkSignature` is needed and has been added to prevent data tampering by the end user that may compromise your app.

**Comment by nimeshjain14331** [comment] 2017-09-21 08:23
I came across the same problem. I found that issue was not due to widget but because the way I implemented it. On the view, I had started a form of my own (ActiveForm) and inserted widget inside the form. Thus, hidden input type "treeManageHash" was not being sent with the post request to "node/manage". The solution is to remove any form outside of the widget as widget creates its own form.

**Comment by kartik-v** [comment] 2017-09-21 08:49
Nesting of forms is treated as INVALiD HTML. Follow HTML markup rules and specs else your code and app behaviour will be broken.

**Comment by nimeshjain14331** [comment] 2017-09-22 12:56
>  I found that issue was not due to widget but because the way I implemented it.
Yup. I figured that. But posted it here just in case anyone else comes across the same issue. Great plugin by the way. Thanks so much.

**Comment by ghenesis** [comment] 2017-10-02 15:34
Does anyone found the solution to this empty HASH problem? In the basic type of setup it appears while trying to add a new node. Every file is up-to-date and the main model is extending the Tree model.

**Comment by nimeshjain14331** [comment] 2017-10-02 16:04
Do ckeck if you are declaring the widget within an ActiveForm or Html form.

**Comment by ghenesis** [comment] 2017-10-02 16:15
@nimeshjain14331 yes!!! brilliant, now I see the poing of nested forms mentioned above -- my mistake! Thanks!

**Comment by kartik-v** [comment] 2017-10-02 17:32
@ghenesis [read this comment](https://github.com/kartik-v/yii2-tree-manager/issues/150#issuecomment-331093749)

**Comment by ghenesis** [comment] 2017-10-02 18:09
@kartik-v, thanks, I have realized what was it all about (encapsulating form in form). 

It may be not very clear in the begining of using this widget, because it's called quite like any other form widget but it turns out to be separated form, which is quite obvious after all :)

**Comment by TomaszGrzmilas** [comment] 2018-06-13 09:36
Hi,

I change nodeView to my own. I want to show articles connected to some category after chose it from left side.  ('nodeView' => '@app/modules/articlemgm/views/article-category/_show_article')

_show_article.php:

echo '<pre>';
print_r($params['node']['id']);
echo '</pre>';

First node is working, but after change i get error: Invalid request signature detected during tree data manage action! Please refresh the page and retry.

Any help ? :)

**Comment by arenovec** [comment] 2018-10-03 11:44
@kartik-v Hi. I have some a problem with tree. I just install and configure plugin and i see text on window like on screen 
http://prntscr.com/l1nnqh
When i click on icon "tree" i have mistake http://prntscr.com/l1no71
Old hash != new hash because in old hash i see different string
OLD HASH
app\models\Treebtn-default/web/index.php?r=treemanager%2Fnode%2Fsave/@kvtree/views/_formw0-nodeselnodenodes<div class="kv-node-message">No valid  are available for display. Use toolbar buttons to add .</div>111111{"id":"w0-nodeform"}{"1":"","2":"","3":"","4":"","5":""}{"submit":"<i class=\"glyphicon glyphicon-floppy-disk\"></i>","reset":"<i class=\"glyphicon glyphicon-repeat\"></i>"}[]"text"{"depth":"","glue":" &raquo; ","activeCss":"kv-crumb-active","untitled":"Untitled"}

**Comment by mtc-toolbox** [comment] 2019-10-13 05:01
After last composer update repeated.

**Comment by kartik-v** [comment] 2019-10-13 05:08
Clean your yii web runtime assets and clean your browser cache and restart hard refresh browser to ensure they are loading the updated JS assets

**Comment by mtc-toolbox** [comment] 2019-10-13 07:23
Ok.
Use: "kartik-v/yii2-tree-manager": "dev-master",

Clear backend\web\assets\

Ctrl-F5 in Chrome.

All fine, thank you !!!
