### ISSUE TITLE
Checkbox Overwrites Name In Admin Settings 

### ISSUE THREAD

**Issue by BillHeaton** [kartik-v/yii2-tree-manager#256] opened 2019-10-08 05:20 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-tree-manager.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/tree-manager) and [demos](http://demos.krajee.com/tree-manager-demo/tree-view).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [x ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Probably reproducible on demo site with a one line addition
2. Add 'displayValue' => 2,  to Widget declaration 
3. Bring the form up.
4. Notice Corruption.
5. Select another node
6. Notice it displays correctly

## Expected behavior and actual behavior

When I follow those steps, I see...
![Yii2_AdminOverwrite](https://user-images.githubusercontent.com/2707561/66369232-69037300-e950-11e9-8496-779e6b0b560b.jpg)

I was expecting...
Normal display as in Step 6.

#### Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer
- [x ] Safari

#### Operating System

- [ ] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-tree-manager version: Latest

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/tree-manager-demo/tree-view)
- [x ] The bug happens consistently across all tested browsers
- [x ] This bug happens when using yii2-tree-manager without other plugins.

**Comment by kartik-v** [comment] 2019-10-08 15:12
I am not able to reproduce this issue. It seems more a CSS/styling issue. Seems you are using some Checkbox styling plugin in your code (based on the screenshot you shared). You may need to check how you are initializing that.

**Comment by BillHeaton** [comment] 2019-10-08 19:31
I agree.  It only happens on the first paint of the detail screen.  It's like something isn't being set on the first pass.  I'll redo it on the "Plain Jane" environment  again.

**Comment by BillHeaton** [comment] 2019-10-09 02:39
Created a new project "testbed."  It has only following requires and their dependencies:
- yiisoft/yii2 (2.0.28)
- yiisoft/yii2-bootstrap4 (2.0.8)              
- kartik-v/yii2-tree-manager (dev-master adca0c8) 

Followed Steps 1-4 and using:
- 'bsVersion' => '4.x',	 
- 'isAdmin' => true, 
- 'displayValue' => 5,

 I'm using site/index.php for the treeview widget. Might be caused in the default Yii2 basic application as its header is messed up from BS4 too.  I'll simplify that and see if the problem goes away.  

If I move to any other node is the management portion displays correctly. same behavior on Firefox and Chrome except the two columns stack L-R correctly.  Only safari moves the detail below treeview.

![Testbed_256](https://user-images.githubusercontent.com/2707561/66446856-07e7a800-ea01-11e9-8eaa-f81b923bae07.jpg)

**Comment by kartik-v** [comment] 2019-10-09 02:42
You need to ensure you do not wrongly have both bootstrap 3 and bootstrap 4 assets loading on your page. Can typically happen if you are using default widgets.

**Comment by BillHeaton** [comment] 2019-10-09 03:27
That opened a big can of worms. Restarting the testbed.  Do you know any good howto's on the process?  If not, I think I'll write one.

**Comment by kartik-v** [comment] 2019-10-09 06:33
If you use all of Krajee widgets - they allow you to selectively load Bootstrap 3 or Bootstrap 4 by setting `bsVersion`. So if you have globally set this to `4.x` all Krajee widgets will load BS4 assets only. But if you use other widgets be careful of their dependency (like yii2-bootstrap loads BS3). Also Yii2 app basic or advanced by default loads yii2 bootstrap assets which loads BS3 libraries.

**Comment by BillHeaton** [comment] 2019-10-09 06:39
Ack.  That was the can of worms I was talking about.  I'll report progress as I do the HowTo.  I want to start with nothing and make it all the way to being Bootstrap4 ready using the basic application.

**Comment by BillHeaton** [comment] 2019-10-09 08:09
Have the bullet points done.  One cosmetic change needed.  Need to flesh out the article.  Relatively painless to do but not for novices.

One in the morning so going to bed.  Will write it up and post tomorrow.

**Comment by kartik-v** [comment] 2019-10-09 09:12
Refer enhancement #258 which includes enhanced styled custom BS4 checkboxes and radios by default now.

**Comment by kartik-v** [comment] 2019-10-09 09:16
Refer enhancement #258 which includes enhanced styled custom BS4 checkboxes and radios by default.  Cross check [updated demo](https://demos.krajee.com/tree-manager-demo/tree-view) as well to see how this renders by default on a pure BS4 environment. Currently closing this issue. But please feel free to record your findings here for others to note. Thanks.

**Closed by kartik-v** 2019-10-09 09:16 UTC
Labels: question

**Comment by BillHeaton** [comment] 2019-10-10 00:29
Howto now online at http://www.winkwinknodnod.net/yii2-bs4/

Will restart the testbed to make it a pure bootstrap4 environment

**Comment by BillHeaton** [comment] 2019-10-10 10:34
@kartik-v Doing the pure bootstrap4 from http://www.winkwinknodnod.net/yii2-bs4/ only had one weirdness.  

yii2-krajee-base/initBsAssets() was selecting bootstrap instead of bootstrap4 which of course didn't exist because it had been uninstalled.  

The fix was to add bsVersion = '4.x' in config/params.php to set it globally instead of in the module or the widget. Which makes sense to me because we only have bootstrap4 in the water.

This one can remain closed.  Feel free to put the howto up where every it makes sense.  There are some other issues but still need to research and they can go into their own pile
